openapi: 3.0.3
info:
  title: Mawhebty platform api
  description: API for mawhebty platform end-points
  version: 1.0.0

servers:
  - url: http://localhost:3000/api/mawhebty-platform/v1
    description: Local development server
  - url: https://talent-scout-mu.vercel.app/
    description: Production server.

security:
  - ApiKeyAuth: []

paths:
  /profile/user:
    get:
      tags:
        - MawhebtyPlatformUserProfile
      summary: get user profile data
      description: get user profile data
      operationId: userProfile
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response with user profile data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfileDataResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /profile/user/follow/{userId}:
    post:
      tags:
        - MawhebtyPlatformUserFollow
      summary: Follow a user
      description: Follow another user
      operationId: followUser
      security:
        - bearerAuth: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successfully followed user
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /profile/user/unfollow/{userId}:
    post:
      tags:
        - MawhebtyPlatformUserFollow
      summary: Unfollow a user
      description: Unfollow a user you're following
      operationId: unfollowUser
      security:
        - bearerAuth: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successfully unfollowed user
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /profile/user/followers:
    get:
      tags:
        - MawhebtyPlatformUserFollow
      summary: Get user followers
      description: Get list of users following the current user
      operationId: getUserFollowers
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of followers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserFollowResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /profile/user/following:
    get:
      tags:
        - MawhebtyPlatformUserFollow
      summary: Get user following
      description: Get list of users the current user is following
      operationId: getUserFollowing
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of following users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserFollowResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /profile/user/saved-items:
    get:
      tags:
        - MawhebtyPlatformUserSavedItems
      summary: Get user saved items
      description: Get user's saved posts, events, and articles
      operationId: getUserSavedItems
      security:
        - bearerAuth: [ ]
      parameters:
        - name: item_type
          in: query
          description: Filter by item type (1=posts, 2=events, 3=articles)
          required: false
          schema:
            type: integer
            enum: [ 1, 2, 3 ]
        - name: page
          in: query
          description: Page number
          required: false
          schema:
            type: integer
            default: 1
        - name: per_page
          in: query
          description: Items per page
          required: false
          schema:
            type: integer
            default: 10
            maximum: 50
      responses:
        '200':
          description: List of saved items
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SavedItemsData'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
      description: API key for authentication
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        code:
          type: string
        timestamp:
          type: string
          format: date-time
      required:
        - error
        - code
        - timestamp

    OTPGenerationResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        nextStep:
          type: string
        verificationUrl:
          type: string
        otpExpiresAt:
          type: string
          format: date-time

    UserProfileDataResponse:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/userProfile'
        category:
          $ref: '#/components/schemas/category'
        subcategory:
          $ref: '#/components/schemas/subcategory'
        talent_type:
          $ref: '#/components/schemas/talentType'

    userProfile:
      type: object
      properties:
        id:
          type: integer
        first_name:
          type: string
        last_name:
          type: string
        contact_person:
          type: string
        contact_phone:
          type: string
        phone:
          type: string
        country_code:
          type: string
        user_status:
          type: integer
        user_role:
          type: integer
        image_url:
          type: string
        short_bio:
          type: string
        age:
          type: integer
        country:
          type: string
        city:
          type: string
        followers:
          type: integer
        following:
          type: integer

    category:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string

    subcategory:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string

    talentType:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string

    UserFollowResponse:
      type: object
      properties:
        userId:
          type: integer
        firstName:
          type: string
        lastName:
          type: string
        imageUrl:
          type: string
        shortBio:
          type: string
        followedAt:
          type: string
          format: date-time

    SavedItemsData:
      type: object
      properties:
        posts:
          type: array
          items:
            $ref: '#/components/schemas/SavedPost'
        events:
          type: array
          items:
            $ref: '#/components/schemas/SavedEvent'
        articles:
          type: array
          items:
            $ref: '#/components/schemas/SavedArticle'

    SavedPost:
      type: object
      properties:
        id:
          type: integer
        owner:
          $ref: '#/components/schemas/SavedItemOwner'
        title:
          type: string
        description:
          type: string
        image_url:
          type: string
        date:
          type: string
          format: date-time
        saved_at:
          type: string
          format: date-time

    SavedEvent:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        location:
          type: string
        location_coordinates:
          type: string
        image_url:
          type: string
        date:
          type: string
          format: date-time
        saved_at:
          type: string
          format: date-time

    SavedArticle:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        date:
          type: string
          format: date-time
        image_url:
          type: string
        category_name:
          type: string
        sub_category_name:
          type: string
        saved_at:
          type: string
          format: date-time

    SavedItemOwner:
      type: object
      properties:
        id:
          type: integer
        first_name:
          type: string
        last_name:
          type: string
        image_url:
          type: string