CREATE TABLE IF NOT EXISTS post_types (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL
);

INSERT INTO post_types (name)
VALUES
 ('PROFILE_VIDEO'),
 ('REEL'),
 ('IMAGE'),
 ('DOCUMENT'),
 ('REGISTRATION_FILE')
ON CONFLICT (name) DO NOTHING;